### ISSUE TITLE
Bug Packet

### ISSUE THREAD

**Issue by Naimado6** [schorschii/OCO-Agent#12]
Hi,
I have some issues for installing some softwares with oco.
If there a known way to install user-wide soft with oco like zoom or VScode 
Or we have to install those system-wide ?

We try to execute the soft with **runas** but we have to specify the password of the user but it's not viable for us
Thank you in advance

**Comment by schorschii** [comment]
I always recommend installing packages system-wide, that's what OCO is made for. You as the administrator want to ensure and enforce that every managed computer has the newest version installed with all security and bug fixes. User-wide installations cannot be easily managed and updated in that way. Also, user-wide installations take up unnecessary space for each user on the computer.

For Zoom, best way for deployment is to use the [MSI installer](https://support.zoom.com/hc/de/article?id=zm_kb&sysparm_article=KB0060417). For VScode, use the ["System Installer"](https://code.visualstudio.com/Download). Other software may not has separate installers but parameters to switch the installation mode (`ALLUSERS=1` or `/ALLUSERS`).

Please note that these kind of requests are not issues regarding OCO. If you need help packaging your software, you can buy commercial support. Please [contact me](https://georg-sieber.de/?page=impressum) if you are interested. With this, you also support the development of this application.

**Comment by Naimado6** [comment]
Thx for the reply 
In some cases we prefer user wide to ensure that the non-admin user can keep his soft update.
But we'll stick with the system wide installation for those softs.
