### ISSUE TITLE
Error with Nextcloud desktop

### ISSUE THREAD

**Issue by Naimado68** [schorschii/OCO-Agent#15]
Hello,

We're trying to start Nextcloud Desktop on Ubuntu, but we keep encountering permission errors with the message "Operation not permitted". Regrettably, we're unable to utilize sudo.

Could you provide guidance on resolving this issue?

Thank you for your help.

**Comment by schorschii** [comment]
Dear @Naimado68 , what was that? Why did you close the issue directly after creating it?

**Comment by Naimado68** [comment]
Hello,
Sorry it's a mistake on my part I went to the wrong github page.

**Comment by schorschii** [comment]
OK no problem. However, feedback for the OCO Agent is appreciated too :)
