### ISSUE TITLE
remote installation on Windows via MeshCentral

### ISSUE THREAD

**Issue by POLYANKA123456** [schorschii/OCO-Agent#16]
Hello, I'm from Quicksign and I am trying to implement a new solution to install OCO remotely with MeshCentral. I want to use a script in powershell. 

I couldn't find a way to use our server-name and agent-key when executing the oco installer. 

We also tried to modify manually the oco-agent.ini file, but it doesn't seem to work either.

Here is the script : 

```$FILE = "C:\Program Files\OCO Agent\oco-agent.ini"
 
mkdir C:\temp
Invoke-WebRequest -Uri "https://github.com/schorschii/OCO-Agent/releases/download/v1.1.0/oco-agent.exe" -OutFile "C:\temp\oco-agent.exe"
 
cd C:\temp
 
.\oco-agent.exe /SILENT
 
Start-Sleep 30
 
# On modifie le fichier oco-agent.ini avec les bons paramètres
((Get-Content -Path $FILE) -replace 'api-url =','api-url = https://oco.quicksign.fr/api-agent.php') | Set-Content -Path $FILE
Add-Content -PATH $FILE "server-key = ******
```

And the linux script (functionnal) : 

```sudo wget https://github.com/schorschii/OCO-Agent/releases/download/v1.1.0/oco-agent.deb
 
echo "oco-agent oco-agent/server-name string oco.quicksign.fr" | sudo debconf-set-selections
echo "oco-agent oco-agent/agent-key string ******" | sudo debconf-set-selections
 
sudo dpkg -i oco-agent.deb
rm -f oco-agent.deb
```

Thanks for your help 
Augustin DESOMBRE

**Comment by schorschii** [comment]
Hi,

on Windows, the setup has a parameter `/LOADINF=<filename>`, as demonstrated [here](https://github.com/schorschii/OCO-Server/blob/master/docs/examples/SetupComplete.cmd). A example setup config can be found [here](https://github.com/schorschii/OCO-Server/blob/master/docs/examples/oco-agent-setup.inf). Note that the setup.inf is not the same file as the regular oco-agent.ini.

More info about automatic agent installation config can be found in the [OS installation docs](https://github.com/schorschii/OCO-Server/blob/master/docs/OS-Installation.md).

Regardless of that, your method of changing the oco-agen.ini after installation should work too, but you need to restart the agent service afterwards.

Kind regards

**Comment by schorschii** [comment]
@POLYANKA123456 does it work now?

**Comment by schorschii** [comment]
Closed due to inactivity...
