### ISSUE TITLE
Agent > 1.0.0 not working on Ubuntu20

### ISSUE THREAD

**Issue by BornTKill** [schorschii/OCO-Agent#25]
Hello @schorschii,

For you information, agent > 1.0.0 are not working on Ubuntu 20

<img width="924" alt="image" src="https://github.com/user-attachments/assets/4e2c6f01-bfcc-40e1-8763-cf1e82d30cc7">

**Comment by schorschii** [comment]
Yes, that's true. 1.0.3 should be the newest version which runs on Ubuntu 20.04. I'm going to update the supported distros in the README.md as I don't plan to add support for those old systems again.
