### ISSUE TITLE
Agent 1.1.3 ARM not working

### ISSUE THREAD

**Issue by BornTKill** [schorschii/OCO-Agent#26]
<img width="451" alt="image" src="https://github.com/user-attachments/assets/be66d85e-2f4c-4e90-8dcd-a66826165d5d">

**Comment by BornTKill** [comment]
Same error with 1.1.0

**Comment by BornTKill** [comment]
The problematic user is on Sonoma 14.5 (Apple M1)
No issue on 1.1.3 for me on Sequoia 15.0.1 (Apple M3)

**Comment by schorschii** [comment]
The issue here is when reading the installed software. This Mac has an application installed which has a bad Info.plist file in it. I fixed it with the linked commit. You may test it when the new version is released. It should print out the bad application too.

**Comment by BornTKill** [comment]
Hello,

can you pre realease the mac agent ?

**Comment by schorschii** [comment]
Yes, done: https://github.com/schorschii/OCO-Agent/releases/tag/v1.1.4
