### ISSUE TITLE
Missing windows build for oco-agent

### ISSUE THREAD

**Issue by t-oster** [schorschii/OCO-Agent#7]
Hi,
I noticed on https://github.com/schorschii/oco-agent/releases the seventh release contained a prebuild oco-agent.ext, but the following releases are missing a windows setup.

Could you add them, because it makes deployment much easier.

**Comment by schorschii** [comment]
Yes, I created a new release just now with all setup files (.exe, .deb & .pkg). Starting with v1.0 (which will come soon), every release will have the prebuilt packages.
